# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  test:
    docker:
    # Use the same Docker base as the project
    - image: python:3.7.3-stretch
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
           - v1-dependencies-{{ checksum "helloworld/requirements.txt" }}
           # fallback to using the latest cache if no exact match is found
           - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
            hadolint --version
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "helloworld/requirements.txt" }}
      # run lint!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint 

  build-image:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build docker image
          command: |
            docker build -t jonezzy/helloworld-app:latest .
      - run:
          name: archive and persist docker image
          command: docker save -o image.tar jonezzy/helloworld-app
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar

  publish-latest:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push jonezzy/helloworld-app:latest

workflows:
  default:
    jobs:
      - test
      - build-image:
          requires:
            - test
      - publish-latest:
          requires:
            - build-image
