# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs: 
  docker: circleci/docker@2.1.2

jobs:
  build-test:
    docker:
    # Use the same Docker base as the project
    - image: python:3.7.3-stretch
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
           - v1-dependencies-{{ checksum "helloworld/requirements.txt" }}
           # fallback to using the latest cache if no exact match is found
           - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
            hadolint --version
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "helloworld/requirements.txt" }}
      # run lint!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint 

workflows:
  default:
    jobs:
      - build-test
      - docker/publish:
          image: $DOCKERHUB_USERNAME/helloworld-app
          requires: [build-test]
