version: 2.1

jobs:
  test:
    docker:
    - image: python:3.7.3-stretch
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
           - v1-dependencies-{{ checksum "helloworld/requirements.txt" }}
           # fallback to using the latest cache if no exact match is found
           - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
            hadolint --version
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "helloworld/requirements.txt" }}
      # run lint!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint 

  build-publish:
    docker:
      - image: cimg/deploy:2022.06.1-node
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build docker image
          command: |
            COMMIT_HASH=$(git log -1 --pretty=%h)
            docker build -t jonezzy/helloworld-app:latest -t jonezzy/helloworld-app:$COMMIT_HASH .
      - run:
          name: publish docker image to docker hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker image push --all-tags jonezzy/helloworld-app

workflows:
  default:
    jobs:
      - test
      - build-publish:
          requires:
            - test
